# Site settings
title: Robert Norris
email: robert.derek.norris@gmail.com
description: > # keep this and put description below
  Product Lead Mobile & Senior Staff Software Engineer
url: "https://wuntunsun.github.io" # the base hostname & protocol for your site
linkedin_url: "https://www.linkedin.com/in/robertdereknorris/"
github_username: wuntunsun
#twitter_username: gamingportfolio
footer_text: "This site uses <a href='https://github.com/gamingportfolio/urban-theme-portfolio'>urban-theme (portfolio)</a>."

# Build settings
markdown: kramdown
permalink: pretty
